# Generated by Django 5.0.2 on 2024-02-25 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
