# Generated by Django 5.0.2 on 2024-07-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
