# Generated by Django 5.0.2 on 2024-07-30 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_app', '0004_alter_transaction_matriculation_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='semester',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
